# Generated by Django 2.2 on 2019-05-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
