# Generated by Django 2.2 on 2019-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190519_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movieId',
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
