# Generated by Django 2.2 on 2019-05-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190519_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='id',
            new_name='movieId',
        ),
    ]
