# Generated by Django 2.2 on 2019-05-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190519_1605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
